FROM php:7.4-fpm

RUN apt update \
    && apt install -y zlib1g-dev g++ git libicu-dev zip libzip-dev zip \
    && docker-php-ext-install intl opcache pdo pdo_mysql \
    && pecl install apcu \
    && docker-php-ext-enable apcu \
    && docker-php-ext-configure zip \
    && docker-php-ext-install zip

WORKDIR /var/www/symfony_docker

#RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN apt-get install sudo

RUN curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh' | sudo -E bash
RUN apt install symfony-cli

# Install amqp php extension 
# Cf. https://stackoverflow.com/a/65345103/1743192
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions \ 
    /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && sync && \
    install-php-extensions amqp

RUN curl -sS https://getcomposer.org/installer | php 
RUN sudo mv composer.phar /usr/bin/composer

RUN apt-get update && apt-get install -y supervisor

RUN apt-get update && apt-get install -y cron

RUN apt-get update && apt-get install -y procps && rm -rf /var/lib/apt/lists/*

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

## Symfony will need to `git init` during setup.
## If we don't set the git user's name and email, 
## Symfony will exit with an error.
#RUN git config --global user.name "Your name" && \ 
#    git config --global user.email "you@example.com"
